import { useEffect, useState } from "react";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  const [secureData, setSecureData] = useState<string>("Loading...");
  const [error, setError] = useState<string | null>(null);

  // Replace with a valid JWT generated by your auth service
  const JWT_TOKEN = "YOUR_JWT_TOKEN_HERE";

  useEffect(() => {
    const fetchSecureData = async () => {
      try {
        const response = await fetch("http://localhost:4000/secure-data", {
          headers: {
            Authorization: `Bearer ${JWT_TOKEN}`,
          },
        });

        if (!response.ok) {
          throw new Error(`Request failed: ${response.status}`);
        }

        const data = await response.json();
        setSecureData(JSON.stringify(data, null, 2));
      } catch (err: any) {
        setError(err.message || "Error fetching data");
      }
    };

    fetchSecureData();
  }, []);

  return (
    <div className="min-h-screen bg-brand text-gray-900">
      {/* HEADER */}
      <Header />

      {/* HERO SECTION */}
      <main>
        <Hero />

        {/* Secure Data Display */}
        <section className="max-w-5xl mx-auto p-6">
          <h2 className="text-xl font-semibold mb-4">Secure Data from Gateway</h2>
          {error ? (
            <p className="text-red-600 font-medium">
              Error: {error} — Ensure backend gateway is running on port 4000 and token is valid.
            </p>
          ) : (
            <pre className="bg-gray-100 p-4 rounded text-sm overflow-x-auto">
              {secureData}
            </pre>
          )}
        </section>

        {/* INDUSTRY SECTION */}
        <section className="max-w-5xl mx-auto p-6">
          <h2 className="text-2xl font-semibold mb-4">
            Transforming Every Industry with Smarter AI Solutions
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            <div className="bg-white p-6 rounded-lg shadow hover:shadow-lg transition">
              Retail — Personalized customer experiences
            </div>
            <div className="bg-white p-6 rounded-lg shadow hover:shadow-lg transition">
              Finance — Fraud detection &amp; smart predictions
            </div>
            <div className="bg-white p-6 rounded-lg shadow hover:shadow-lg transition">
              Healthcare — Faster diagnosis &amp; workflow
            </div>
          </div>
        </section>

        {/* PRICING SECTION */}
        <section className="max-w-5xl mx-auto p-6">
          <h3 className="text-xl font-semibold mb-4">Simple, Transparent Pricing</h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            <div className="bg-white p-6 rounded-lg shadow hover:shadow-lg transition">
              <h4 className="font-bold text-lg mb-2">Starter — $0/mo</h4>
              <p className="text-sm text-gray-600">
                Basic features for small teams or personal use.
              </p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow hover:shadow-lg transition">
              <h4 className="font-bold text-lg mb-2">Pro — $49/mo</h4>
              <p className="text-sm text-gray-600">
                Advanced tools and analytics for growing businesses.
              </p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow hover:shadow-lg transition">
              <h4 className="font-bold text-lg mb-2">Enterprise — $99/mo</h4>
              <p className="text-sm text-gray-600">
                Full suite of automation and premium support.
              </p>
            </div>
          </div>
        </section>
      </main>

      {/* FOOTER */}
      <footer className="max-w-5xl mx-auto p-6 text-center text-sm text-gray-500">
        © {new Date().getFullYear()} Optivize AI — Demo
      </footer>
    </div>
  );
}
